name: hello-app-tls-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hello-app-tls-ci.yml'
      - 'hello-app-tls/**'
  pull_request:
    paths:
      - '.github/workflows/hello-app-tls-ci.yml'
      - 'hello-app-tls/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build hello-app-tls container
        run: |
          cd hello-app-tls
          docker build --tag hello-app-tls .
          
      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: atiftaqi/gcp-deployment
         registry: docker.io
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
         image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
         format: 'table'
         exit-code: '1'
         ignore-unfixed: true
         vuln-type: 'os,library'
         severity: 'MEDIUM,HIGH,CRITICAL'
